---
title: "lab_8"
author: "Lauren Berny, Adriana Conn, Mavis Gallo, Aubrey Green, & Shawn McWeenie"
date: "11/11/2021"
output: pdf_document
<<<<<<< Updated upstream
=======
bibliography: references.bib
>>>>>>> Stashed changes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.height= 8, fig.width= 6.5)

library(tidyverse)
library(janitor)
library(here)
library(rio)
library(dplyr)
library(ggplot2)
<<<<<<< Updated upstream
library(kableExtra)
=======

>>>>>>> Stashed changes
```


```{r commit_1}
star <- import(here("data", "star.csv"),
  setclass = "tbl_df") %>%
  clean_names()
```


```{r commit_2}

```


```{r commit_3}
<<<<<<< Updated upstream
star %>%
 group_by(sex, frl) %>%
 summarize(math_mean = mean(tmathss), math_sd = sd(tmathss), rdg_mean = mean(treadss), rdg_sd = sd(treadss)) %>%
 kable(digits = 2,
       booktabs = TRUE) %>%
 kable_styling()
            
```
The table above shows that both boys and girls who received free/reduced lunch tended to score lower on average in math and reading scores compared to boys and girls who did not receive free/reduced lunch.
=======

```

>>>>>>> Stashed changes

```{r commit_4}

```

<<<<<<< Updated upstream
=======
\newpage

#References
>>>>>>> Stashed changes
